validate-target:
    @ rustc --print cfg --target riscv-pathos.json

build:
    @ cargo build --release

dump:
    @ riscv64-linux-objdump -D target/riscv-pathos/release/usercode -j .text

dump-all:
    @ riscv64-linux-objdump -D target/riscv-pathos/release/usercode

readelf:
    @ riscv64-linux-readelf -a target/riscv-pathos/release/usercode

copy:
    @ cp target/riscv-pathos/release/usercode ../src/app